project_name: dotenv
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./main.go
    binary: dotenv
    goos:
    - windows
    - darwin
    - linux
    ignore:
    - goos: darwin
      goarch: 386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
- image_templates:
  - "levibostian/dotenv:latest"
  - "levibostian/dotenv:{{ .Tag }}"
  
brews:
- name: dotenv
  tap:
    owner: levibostian
    name: homebrew-tap
  folder: Formula
  license: "MIT"
  homepage: "https://github.com/levibostian/dotenv"

# snapcrafts:
#   - name: purslane
#     publish: true
#     summary: Scalable, flexible, affordable, and safe way to perform periodic tasks.
#     description: Run a single docker container inside of a cloud server as if it was a CLI.
#     grade: stable
#     confinement: strict
#     license: MIT
#     apps:
#       purslane:
#         plugs: ["home", "network", "config-file"]
#     plugs:
#       config-file:
#         interface: personal-files
#         read:      
#         - $HOME/.purslane

# skip changelog generation because semantic release does that for us already. Go releaser updates existing github releases if there is one.
changelog:
  skip: true 