package lang

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/levibostian/dotenv/types"
)

type Kotlin struct {
}

var kotlinFileTemplate = `package %s

/**
 * This file is automatically generated. Do not modify. 
 */
object Env {
    %s
}
`

func (lang Kotlin) GetInfo() LangInfo {
	return LangInfo{
		Name:               "kotlin",
		RequirePackageName: true,
	}
}

func (lang Kotlin) IsFilenameValid(filename string) bool {
	return strings.HasSuffix(filename, ".kt")
}

func (lang Kotlin) ParseSourceCodeLine(line string) []string {
	var environmentVariablesFound = []string{}

	// Regex matcher: https://regexr.com/4rf2s
	for _, variableMatch := range regexp.MustCompile("Env\\.[a-z]\\w*").FindAllString(line, -1) {
		// get `fooBar` from `Env.fooBar`
		splitVariableMatch := strings.Split(variableMatch, ".")[1]

		// convert `fooBar` to `FOO_BAR`
		envVarMatch := strcase.ToScreamingSnake(splitVariableMatch)

		environmentVariablesFound = append(environmentVariablesFound, envVarMatch)
	}

	return environmentVariablesFound
}

func (lang Kotlin) GetOutputFileName() string {
	return "Env.kt"
}

func (lang Kotlin) GetOutputFile(values map[string]string, options types.GenerateOptions) string {
	var variableLines = []string{}

	// sort the variables for more predictable tests and make the file easier to read by dev
	keys := make([]string, 0, len(values))
	for k := range values {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, key := range keys {
		value := values[key]
		variable := key

		variableLines = append(variableLines, fmt.Sprintf("val %s = \"%s\"", strcase.ToLowerCamel(strings.ToLower(variable)), value))
	}

	return fmt.Sprintf(kotlinFileTemplate, options.PackageName, strings.Join(variableLines, "\n    "))
}
