package earth.levi.dotenv;

/**
 * This file is automatically generated. Do not modify. 
 */
public final class Env {
    public static String barBar = "hello";
    public static String fooFoo = "world";
    public static String bazBaz = "";
}
