package earth.levi.dotenv;

/**
 * This file is automatically generated. Do not modify. 
 */
public final class Env {
    public static String javaFoo = "java-here";
    public static String kotlinBar = "hello";
    public static String kotlinFoo = "world";
}
