name: Deploy 
on: 
  push:    
    branches: ['main', 'beta', 'alpha']

jobs:
  test:
    name: Test 
    runs-on: ubuntu-latest
    # skip if '[skip ci]' exists in commit message 
    if: ${{ !contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[skip ci]') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.7'
      # Docker login is required by goreleaser           
      - uses: docker/login-action@v1
        with:
          username: levibostian
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install dependencies        
        run: |          
          go install github.com/goreleaser/goreleaser
      - name: Deploy via semantic release 
        uses: cycjimmy/semantic-release-action@v2
        with: 
          # version numbers below can be in many forms: M, M.m, M.m.p
          semantic_version: 17
          extra_plugins: |
            @semantic-release/commit-analyzer@8
            @semantic-release/release-notes-generator@9
            @semantic-release/changelog@5
            @semantic-release/git@9
            @semantic-release/github@7
            @semantic-release/exec@5
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PUSH_TOKEN }}          