name: Test
on: 
  push:    
    branches:
      - '*' # because we use code coverage, we want to have tests run on all branches to generate a report on it. 
    tags-ignore: # Don't run tests on tags as tags are made off of main branch. 
      - '*'
  pull_request: # Run on all PRs. 
    branches:
      - '*'

jobs:
  test:
    name: Test 
    runs-on: ubuntu-latest
    # skip if '[skip ci]' exists in commit message 
    if: ${{ !contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[skip ci]') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.7'
      - name: Install test dependencies
        run: |
          go get gotest.tools/gotestsum
          go mod download
      - name: Build # it's good to test the code compiles but e2e tests also require the binary to exist. 
        run:  go build -ldflags "-X main.version=1.0.1"
      - name: Run tests 
        run:  gotestsum --junitfile unit-tests.xml
      - name: Process test results 
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '*tests.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_failure: true 
          require_tests: true 
        if: ${{ always() }} # if running tests fails, we still want to parse the test results 